### ISSUE TITLE
Home page not responsive on mobile

### ISSUE THREAD

**Issue by d3ward** [useaurora/aurora#58]
On mobile the table is not responsive , is not possible to reach the View Dashboard button on row element

![photo5895371616748156425 (1)](https://user-images.githubusercontent.com/39910418/120706964-07473380-c4ba-11eb-88d8-283f79a33cee.jpg)

**Comment by itsrennyman** [comment]
Woops! Your're right!

I'll work on a responsive version oh that list.

Thank you.

**Comment by nkootstra** [comment]
I had the same problem and fixed it. Need to do some cleanup and testing before creating a PR. 

![Screen Recording 2021-06-05 at 18 02 23](https://user-images.githubusercontent.com/545768/120897864-8b1f2e00-c628-11eb-9009-f07f6b99b3e4.gif)

**Comment by d3ward** [comment]
I think a good solution can be a responsive card-grid style. 
On desktop 4 , 3/2 on tablet and 1 in mobile . The cards should be simple like : 

<img width="776" alt="Schermata 2021-06-05 alle 18 40 55" src="https://user-images.githubusercontent.com/39910418/120898962-93c63300-c62d-11eb-8cf5-b98f42da1aeb.png">

**Comment by nkootstra** [comment]
@d3ward I had the same idea but you'd have to combine the search box as well. Maybe I can work out something tomorrow

**Comment by itsrennyman** [comment]
In my opinion the card grid as you mentioned is quite better than the table view. An user usually have 2 or 3 websites to track, and also in case he has 10 websites, the tables would still be useless.

Maybe i can look for some dribbble examples.

**Comment by itsrennyman** [comment]
With the 1.0.0 release, this problem was fixed.

Now it works also on mobile.

Thank you all!

![scrnli_24_06_2021_22-02-05](https://user-images.githubusercontent.com/9286706/123551192-03cd6200-d771-11eb-9bf4-685e4abf7b67.png)
