### ISSUE TITLE
My selfhosted Aurora app stopped working 

### ISSUE THREAD

**Issue by d3ward** [useaurora/aurora#62]
After update with fetch upstream , my Aurora webapp is not working anymore .
Login , home dashboard or anything throw an error connection to server with 404 ( i can see that from devtools ) 
I see that with new version a setup section has been added but even this is not working
I checked the database on Heroku and seems active .

Any helps ?  Im missing something from new version of Aurora ?
I have a deploy on https://aurora-drab.vercel.app/

**Comment by crax0** [comment]
Got the same problem on my local docker instance... 
Started the container like described in the docs but once i try to click "Initialize Database!" it fails with 404...

**Comment by itsrennyman** [comment]
Hello!

I'm personally talking with @d3ward via email about solving his problem, so @crax0 can you please give me a little more details about your problem?

Thank you so much

**Comment by crax0** [comment]
So first im going to copy the example docker-compose.yml (https://docs.useaurora.app/getting-started/installation-1/installation-1/docker-installation) into my docker-compose.yml. After that im starting the container with docker-compose up. Now i browse to "http://localhost:3000/setup" and click on "Initialize Database!" but nothing happens. If i check dev tools in chrome, i see that the request to "http://localhost:3000/v2/initialize/database" fails with error code 404. Docker log says "postgres_1  | 2021-06-30 21:41:59.334 UTC [1] LOG:  database system is ready to accept connections".
<img width="1680" alt="Bildschirmfoto 2021-06-30 um 23 45 02" src="https://user-images.githubusercontent.com/15628197/124035783-50c56880-d9fd-11eb-898b-dd4df4cf3eb8.png">

**Comment by itsrennyman** [comment]
Ok, i think is a problem connected to the issue #65, please i've made a release some minutes ago, pull again the ui image and rebuild it. 

The problem was that the NEXT_PUBLIC_API_URL in the environment section of the docker-compose was not taken, now it works.

Please try again and let me know!

**Comment by crax0** [comment]
Its working now! Thanks alot @itsrennyman ❤️

**Comment by itsrennyman** [comment]
@d3ward please upgrade your up and api module to v1.1.0, and try again, I've added also the JWT support, you can check it on the docs!

https://www.useaurora.app/docs/advanced/authentication

Let me know if it's ok.

**Comment by d3ward** [comment]
Thank you ! It's working 👍
